import re
import datetime
import os

# Configuration
INPUT_LOG = "/app/bin/mating_rituals.log"
OUTPUT_MD = "opensim-0.9.3.libremetaverse-2.0.0.mating_rituals_generated.md"

# Mappings from Raw Signal to Narrative
# (Side, Component, Signal Snippet) -> Narrative Description
NARRATIVE_MAP = [
    # Part I: Login
    (r"\[CLIENT\] \[LOGIN\] START", "The client begins the login process for `Test User`."),
    (r"\[SERVER\] \[LOGIN\] RECV XML-RPC login_to_simulator", "The server receives the XML-RPC request containing the user's name and viewer details."),
    (r"\[SERVER\] \[LOGIN\] AUTH SUCCESS", "The server authenticates the user credentials against the User Account Service."),
    (r"\[SERVER\] \[CAPS\] REGISTER SEED", "The server registers a specific \"Seed Capability\" URL for this session. This will be the secure HTTP channel for future non-realtime communication."),
    (r"\[SERVER\] \[LOGIN\] CIRCUIT PROVISION", "The server provisions a `CircuitCode` on the destination region."),
    (r"\[SERVER\] \[LOGIN\] SEND XML-RPC Response", "The server responds with `Success`, the `CircuitCode`, the `SessionID`, and the Region's IP/Port."),
    (r"\[CLIENT\] \[LOGIN\] PROGRESS ConnectingToSim", "The client acknowledges the successful login and prepares to connect to the simulator."),

    # Part II: Handshake
    (r"\[CLIENT\] \[UDP\] CONNECTED", "The client opens a UDP socket to the server's IP."),
    (r"\[SERVER\] \[UDP\] RECV UseCircuitCode", "The server receives the first critical packet. It contains the `CircuitCode` and `SessionID`. The server validates this against the provisioned circuit from Part I."),
    (r"\[SERVER\] \[UDP\] SEND RegionHandshake", "Upon validation, the server sends the `RegionHandshake` packet, detailing region flags and parameters."),
    (r"\[SERVER\] \[UDP\] SEND AgentMovementComplete", "The server places the avatar in the world (Position calculated) and informs the client."),
    (r"\[CLIENT\] \[UDP\] RECV RegionHandshake", "The client receives the region parameters."),

    # Part III: Caps
    (r"\[CLIENT\] \[CAPS\] EQ RUNNING", "The client connects to the Event Queue (EQ) via the Capabilities system. This is a long-polling HTTP connection used for server-to-client events."),

    # Part IV: World
    (r"\[CLIENT\] \[UDP\] RECV ObjectUpdate", "The client receives packets describing objects in the scene."),
    (r"\[CLIENT\] \[UDP\] RECV LayerData", "The client receives a stream of terrain patches (LayerData packets) to build the ground geometry.")
]

def generate_header():
    return """# OpenSim Client/Server Mating Rituals (Naturalist Edition)

*This document captures the raw "DX story" of the connection sequence between an OpenSim Server and a LibreMetaverse Client, as observed by a neutral 3rd party observer. It utilizes "benign logging probes" inserted at strategic architectural junctions to record the actual signals exchanged.*

## Prologue: The Environment
- **Server**: OpenSim (Instrumented)
- **Client**: LibreMetaverse Test Harness (Instrumented)
- **Protocol**: HTTP (XML-RPC), UDP, HTTP (Caps)

---
"""

def generate_footer():
    return "\n---\n\n*Generated by MatingRitualLogger instrumentation.*"

def parse_log_line(line):
    # Match standard format: date time [MATING RITUAL] [SIDE] [COMP] SIGNAL | PAYLOAD
    # Example: 2025-12-18 05:26:20.573 [MATING RITUAL] [SERVER] [UDP] RECV UseCircuitCode | CircuitCode: 1197876940
    match = re.search(r'\[MATING RITUAL\] (\[.+?\]) (\[.+?\]) (.+?)( \| (.+))?$', line)
    if match:
        side = match.group(1)
        comp = match.group(2)
        signal = match.group(3).strip()
        payload = match.group(5)
        return side, comp, signal, payload
    return None

def process_logs():
    story = []

    seen_patterns = set()

    if not os.path.exists(INPUT_LOG):
        return f"Error: Log file not found at {INPUT_LOG}"

    with open(INPUT_LOG, 'r') as f:
        lines = f.readlines()

    current_chapter = ""

    for line in lines:
        if "[MATING RITUAL]" not in line:
            continue

        parsed = parse_log_line(line)
        if not parsed:
            continue

        side, comp, signal, payload = parsed
        full_tag = f"{side} {comp} {signal}"

        # Reset if new session start
        if "START" in signal and "LOGIN" in comp:
            seen_patterns.clear()
            story = [] # Clear previous story, only keep latest
            current_chapter = ""

        # Determine Chapter
        new_chapter = ""
        if "LOGIN" in comp: new_chapter = "## Part I: The Login Sequence (HTTP/XML-RPC)"
        elif "UDP" in comp and ("Connect" in signal or "Circuit" in signal or "Handshake" in signal): new_chapter = "## Part II: The Handshake (UDP)"
        elif "CAPS" in comp: new_chapter = "## Part III: The Private Channel (Capabilities)"
        elif "UDP" in comp and ("Object" in signal or "Layer" in signal or "Movement" in signal): new_chapter = "## Part IV: World Materialization (UDP Stream)"

        # Only switch chapter if we progress forward (simple heuristic)
        if new_chapter and new_chapter != current_chapter:
            # Don't switch back to Login from World (unless restarted, handled above)
            if "Part I" in new_chapter and "Part IV" in current_chapter: continue
            current_chapter = new_chapter
            story.append(f"\n{current_chapter}")

        # Match against Narrative Map
        description = None
        matched_pattern = None
        for pattern, narrative in NARRATIVE_MAP:
            if re.search(pattern, full_tag):
                matched_pattern = pattern
                description = narrative
                break

        if description and matched_pattern:
            if matched_pattern not in seen_patterns:
                seen_patterns.add(matched_pattern)

                # Format: 1. **[TAG]**: Description
                entry = f"1.  **{side} {comp} {signal}**: {description}"
                # Inject payload data dynamically if available
                if payload:
                    clean_payload = payload.strip()
                    if "Pos:" in clean_payload: entry = entry.replace("(Position calculated)", f"(Position: `{clean_payload}`)")
                    if "CircuitCode:" in clean_payload: entry = entry.replace("CircuitCode`", f"CircuitCode` ({clean_payload})")

                story.append(entry)

    return "\n".join(story)

def main():
    content = generate_header()
    content += process_logs()
    content += generate_footer()

    with open(OUTPUT_MD, 'w') as f:
        f.write(content)

    print(f"Generated {OUTPUT_MD}")

if __name__ == "__main__":
    main()
